let DATA = window.__STOCK_DATA__;
const $ = (s)=>document.querySelector(s);
const fmt = (v)=> typeof v === 'number' ? v.toFixed(2) : v;
function get(obj,path){return path.split('.').reduce((o,k)=>o&&o[k],obj)}
function bind(){document.querySelectorAll('[data-bind]').forEach(el=>{el.textContent=fmt(get(DATA,el.dataset.bind));});
let change = Number(DATA.stock.change || 0);
let directionClass = change > 0 ? 'up' : change < 0 ? 'down' : 'yellow';
$('#priceValue').className = directionClass;
$('#changeChip').className = directionClass;
$('#changeArrow').textContent = change > 0 ? '▲' : change < 0 ? '▼' : '＝';
$('#maText').textContent=`MA5 ${DATA.technical.ma5}　MA20 ${DATA.technical.ma20}　MA60 ${DATA.technical.ma60}　近期高點 ${DATA.technical.high}`;
$('#rsiText').textContent=`RSI ${DATA.technical.rsi}`;
$('#macdText').textContent=`DIF ${DATA.technical.macd.dif}　DEA ${DATA.technical.macd.dea}　MACD ${DATA.technical.macd.hist}`;
$('#kdText').textContent=`K ${DATA.technical.kd.k}　D ${DATA.technical.kd.d}`;
$('#adviceBullets').innerHTML=DATA.advice.bullets.map(x=>`<li>${x}</li>`).join('');
$('#longView').innerHTML=DATA.advice.long_view.map(x=>`<li>${x}</li>`).join('');
$('#riskList').innerHTML=(DATA.advice.risks||[{category:'綜合',text:DATA.advice.risk}]).slice(0,5).map(r=>`<li><b>${r.category}</b><span>${r.text}</span></li>`).join('');
$('#paths').innerHTML=`<p><b class="down">上漲路徑：</b><br>${DATA.advice.paths.up}</p><p><b class="yellow">回檔路徑：</b><br>${DATA.advice.paths.pullback}</p><p><b class="up">轉弱路徑：</b><br>${DATA.advice.paths.weak}</p>`;
}
function svgLine(svg,x1,y1,x2,y2,cls='gridline'){let l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('class',cls);svg.appendChild(l);return l}
function svgText(svg,x,y,t,anchor='start',fill){let e=document.createElementNS('http://www.w3.org/2000/svg','text');e.setAttribute('x',x);e.setAttribute('y',y);e.setAttribute('text-anchor',anchor);if(fill)e.setAttribute('fill',fill);e.textContent=t;svg.appendChild(e);return e}
function path(svg,pts,cls,color,width=2){let p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',pts.map((pt,i)=>(i?'L':'M')+pt[0].toFixed(1)+' '+pt[1].toFixed(1)).join(' '));p.setAttribute('fill','none');p.setAttribute('stroke',color);p.setAttribute('stroke-width',width);p.setAttribute('class',cls||'');svg.appendChild(p);return p}
function setupSvg(id,w=400,h=200){let svg=$(id);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);for(let i=0;i<5;i++){svgLine(svg,38,12+i*(h-32)/4,w-8,12+i*(h-32)/4);svgLine(svg,38+i*(w-54)/4,12,38+i*(w-54)/4,h-20)}return {svg,w,h,L:38,T:12,R:w-8,B:h-20}}
function drawK(){let {svg,w,h,L,T,R,B}=setupSvg('#kChart',420,248), d=DATA.ohlc;let min=Math.min(...d.map(x=>x.low)), max=Math.max(...d.map(x=>x.high));let y=v=>B-(v-min)/(max-min)*(B-T);let step=(R-L)/d.length;[min,(min+max)/2,max].forEach(v=>svgText(svg,R-2,y(v)-2,v.toFixed(0),'end'));
let closes=[];d.forEach((c,i)=>{let x=L+i*step+step/2;svgLine(svg,x,y(c.low),x,y(c.high),c.close>=c.open?'candle-up':'candle-down');let rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x-step*.28);rect.setAttribute('y',Math.min(y(c.open),y(c.close)));rect.setAttribute('width',Math.max(2,step*.56));rect.setAttribute('height',Math.max(2,Math.abs(y(c.open)-y(c.close))));rect.setAttribute('class',c.close>=c.open?'candle-up':'candle-down');svg.appendChild(rect);closes.push([x,y(c.close)]);let vh=(c.volume/6000)*42;let vr=document.createElementNS('http://www.w3.org/2000/svg','rect');vr.setAttribute('x',x-step*.28);vr.setAttribute('y',B-vh);vr.setAttribute('width',Math.max(2,step*.56));vr.setAttribute('height',vh);vr.setAttribute('class',c.close>=c.open?'bar-up':'bar-down');svg.appendChild(vr)});
path(svg,closes.slice(4).map((_,idx)=>{let arr=closes.slice(idx,idx+5);return [arr[4][0],arr.reduce((s,p)=>s+p[1],0)/5]}),'ma5','#ffd45a',1.6);path(svg,closes.slice(19).map((_,idx)=>{let arr=closes.slice(idx,idx+20);return [arr[19][0],arr.reduce((s,p)=>s+p[1],0)/20]}),'ma20','#39a9ff',1.4);path(svg,closes.slice(39).map((_,idx)=>{let arr=closes.slice(idx,idx+40);return [arr[39][0],arr.reduce((s,p)=>s+p[1],0)/40]}),'ma60','#b064ff',1.2);
svgText(svg,L+22,y(DATA.technical.low)+12,'近期低點 '+DATA.technical.low,'start','#18d96b');svgText(svg,R-120,y(DATA.technical.high)-8,'近期高點 '+DATA.technical.high,'start','#ff3b3b')}
function seriesRows(key){return (DATA.technical.series||[]).map((r,i)=>({...r,i})).filter(r=>Number.isFinite(r[key]))}
function drawRsi(){let {svg,L,T,R,B}=setupSvg('#rsiChart',420,64), rows=seriesRows('rsi');if(!rows.length)return;let x=r=>L+r.i*(R-L)/Math.max(1,(DATA.technical.series.length-1)), y=v=>B-v/100*(B-T);[30,70].forEach(v=>svgLine(svg,L,y(v),R,y(v),'axis'));path(svg,rows.map(r=>[x(r),y(r.rsi)]),'','#ffd45a',2);svgText(svg,R-4,T+10,'30 / 70','end','#ffd45a')}
function drawMacd(){let {svg,L,T,R,B}=setupSvg('#macdChart',420,64), rows=DATA.technical.series||[];let vals=rows.flatMap(r=>[r.macd_dif,r.macd_dea,r.macd_hist]).filter(Number.isFinite);if(!vals.length)return;let bound=Math.max(...vals.map(v=>Math.abs(v)))||1, mid=(T+B)/2, x=i=>L+i*(R-L)/Math.max(1,rows.length-1), y=v=>mid-v/bound*(B-T)/2;svgLine(svg,L,mid,R,mid,'axis');rows.forEach((r,i)=>{if(!Number.isFinite(r.macd_hist))return;let h=y(r.macd_hist), rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x(i)-2);rect.setAttribute('y',Math.min(h,mid));rect.setAttribute('width',4);rect.setAttribute('height',Math.max(1,Math.abs(h-mid)));rect.setAttribute('class',r.macd_hist>=0?'bar-up':'bar-down');svg.appendChild(rect)});path(svg,rows.map((r,i)=>Number.isFinite(r.macd_dif)?[x(i),y(r.macd_dif)]:null).filter(Boolean),'','#ffd45a',2);path(svg,rows.map((r,i)=>Number.isFinite(r.macd_dea)?[x(i),y(r.macd_dea)]:null).filter(Boolean),'','#39a9ff',2)}
function drawKd(){let {svg,L,T,R,B}=setupSvg('#kdChart',420,64), rows=DATA.technical.series||[];let kRows=rows.map((r,i)=>({...r,i})).filter(r=>Number.isFinite(r.kd_k));if(!kRows.length)return;let x=r=>L+r.i*(R-L)/Math.max(1,rows.length-1), y=v=>B-v/100*(B-T);[20,80].forEach(v=>svgLine(svg,L,y(v),R,y(v),'axis'));path(svg,kRows.map(r=>[x(r),y(r.kd_k)]),'','#ffd45a',2);path(svg,kRows.filter(r=>Number.isFinite(r.kd_d)).map(r=>[x(r),y(r.kd_d)]),'','#39a9ff',2);svgText(svg,R-4,T+10,'K / D','end','#ffd45a')}
function drawChip(){let {svg,w,h,L,T,R,B}=setupSvg('#chipChart',360,195);let rows=[...DATA.chips.institutional].reverse();let max=650,min=-650;let y=v=>B-(v-min)/(max-min)*(B-T), zero=y(0), step=(R-L)/rows.length;svgLine(svg,L,zero,R,zero,'axis');rows.forEach((r,i)=>{let x=L+i*step+6;[['foreign','#39a9ff'],['trust','#ff3b3b'],['dealer','#b064ff'],['total','#18d96b']].forEach(([k,c],j)=>{let v=r[k], yy=y(v);let rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x+j*5);rect.setAttribute('y',Math.min(yy,zero));rect.setAttribute('width',4);rect.setAttribute('height',Math.max(1,Math.abs(yy-zero)));rect.setAttribute('fill',c);svg.appendChild(rect)});svgText(svg,x,B+12,r.date.slice(3),'middle')});let priceRows=[...(DATA.chips.price||[])].reverse();let closes=priceRows.map(r=>Number(r.close)).filter(Number.isFinite);if(closes.length){let pMin=Math.min(...closes),pMax=Math.max(...closes);let pad=(pMax-pMin)*.12||1;pMin-=pad;pMax+=pad;let py=v=>B-(v-pMin)/(pMax-pMin)*(B-T);let pricePts=priceRows.map((r,i)=>[L+i*step+step/2,py(Number(r.close))]);path(svg,pricePts,'','#ffd45a',3);pricePts.forEach((pt,i)=>{if(i===0||i===pricePts.length-1)svgText(svg,pt[0],pt[1]-6,priceRows[i].close.toFixed(1),'middle','#ffd45a')})}svgText(svg,L,T+8,'外資 投信 自營商 合計 / 收盤價','#ffd45a')}
function drawBrokerFlow(){let b=DATA.chips.brokers||{top_buy:[],top_sell:[],summary:{},warning:'尚未接入分點資料'};$('#brokerDate').textContent=b.date?`(${b.date})`:'';let list=(rows,cls)=>`<div class="broker-list ${cls}">${rows.slice(0,5).map(r=>`<div class="broker-row"><span>${r.broker}</span><b class="${r.net>=0?'up':'down'}">${r.net>0?'+':''}${r.net}</b></div>`).join('')||'<div class="broker-empty">待接官方資料</div>'}</div>`;$('#brokerFlow').innerHTML=`<div><div class="broker-head up">買超前五大</div>${list(b.top_buy||[],'buy')}</div><div><div class="broker-head down">賣超前五大</div>${list(b.top_sell||[],'sell')}</div>`;let s=b.summary||{};$('#brokerStats').innerHTML=`<span>買集中 ${(s.buy_concentration*100||0).toFixed(0)}%</span><span>賣集中 ${(s.sell_concentration*100||0).toFixed(0)}%</span><span>Top5 淨額 ${(s.net_top5||0)>0?'+':''}${s.net_top5||0} 張</span>`;$('#brokerWarning').textContent=b.warning||''}
function drawTables(){let inst='<tr><th>日期</th><th>外資</th><th>投信</th><th>自營商</th><th>合計</th></tr>'+DATA.chips.institutional.slice(0,5).map(r=>`<tr><td>${r.date}</td>${['foreign','trust','dealer','total'].map(k=>`<td class="${r[k]>=0?'up':'down'}">${r[k]}</td>`).join('')}</tr>`).join('');$('#instTable').innerHTML=inst;drawBrokerFlow();let avg=DATA.scores.reduce((s,r)=>s+r.stars,0)/Math.max(1,DATA.scores.length);$('#overallStars').textContent='★'.repeat(Math.round(avg))+'☆'.repeat(5-Math.round(avg));$('#scoreTable').innerHTML=DATA.scores.map(r=>`<div class="score-row"><span>${r.item}</span><b class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</b><em>${r.comment}</em></div>`).join('')}
function init(){bind();drawK();drawRsi();drawMacd();drawKd();drawChip();drawTables();document.body.dataset.ready='1'}
if(DATA) init();
