let DATA = window.__STOCK_DATA__;
const $ = (s)=>document.querySelector(s);
const fmt = (v)=> typeof v === 'number' ? v.toFixed(2) : v;
function get(obj,path){return path.split('.').reduce((o,k)=>o&&o[k],obj)}
function bind(){document.querySelectorAll('[data-bind]').forEach(el=>{el.textContent=fmt(get(DATA,el.dataset.bind));});
$('#maText').textContent=`MA5 ${DATA.technical.ma5}　MA20 ${DATA.technical.ma20}　MA60 ${DATA.technical.ma60}　近期高點 ${DATA.technical.high}`;
$('#rsiText').textContent=`RSI ${DATA.technical.rsi}`;
$('#macdText').textContent=`DIF ${DATA.technical.macd.dif}　DEA ${DATA.technical.macd.dea}　MACD ${DATA.technical.macd.hist}`;
$('#kdText').textContent=`K ${DATA.technical.kd.k}　D ${DATA.technical.kd.d}`;
$('#adviceBullets').innerHTML=DATA.advice.bullets.map(x=>`<li>${x}</li>`).join('');
$('#longView').innerHTML=DATA.advice.long_view.map(x=>`<li>${x}</li>`).join('');
$('#paths').innerHTML=`<p><b class="down">① 上漲路徑：</b><br>${DATA.advice.paths.up}</p><p><b class="yellow">② 回檔路徑：</b><br>${DATA.advice.paths.pullback}</p><p><b class="up">③ 轉弱路徑：</b><br>${DATA.advice.paths.weak}</p>`;
}
function svgLine(svg,x1,y1,x2,y2,cls='gridline'){let l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('class',cls);svg.appendChild(l);return l}
function svgText(svg,x,y,t,anchor='start',fill){let e=document.createElementNS('http://www.w3.org/2000/svg','text');e.setAttribute('x',x);e.setAttribute('y',y);e.setAttribute('text-anchor',anchor);if(fill)e.setAttribute('fill',fill);e.textContent=t;svg.appendChild(e);return e}
function path(svg,pts,cls,color,width=2){let p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',pts.map((pt,i)=>(i?'L':'M')+pt[0].toFixed(1)+' '+pt[1].toFixed(1)).join(' '));p.setAttribute('fill','none');p.setAttribute('stroke',color);p.setAttribute('stroke-width',width);p.setAttribute('class',cls||'');svg.appendChild(p);return p}
function setupSvg(id,w=400,h=200){let svg=$(id);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);for(let i=0;i<5;i++){svgLine(svg,38,12+i*(h-32)/4,w-8,12+i*(h-32)/4);svgLine(svg,38+i*(w-54)/4,12,38+i*(w-54)/4,h-20)}return {svg,w,h,L:38,T:12,R:w-8,B:h-20}}
function drawK(){let {svg,w,h,L,T,R,B}=setupSvg('#kChart',420,248), d=DATA.ohlc;let min=Math.min(...d.map(x=>x.low)), max=Math.max(...d.map(x=>x.high));let y=v=>B-(v-min)/(max-min)*(B-T);let step=(R-L)/d.length;[min,(min+max)/2,max].forEach(v=>svgText(svg,R-2,y(v)-2,v.toFixed(0),'end'));
let closes=[];d.forEach((c,i)=>{let x=L+i*step+step/2;svgLine(svg,x,y(c.low),x,y(c.high),c.close>=c.open?'candle-up':'candle-down');let rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x-step*.28);rect.setAttribute('y',Math.min(y(c.open),y(c.close)));rect.setAttribute('width',Math.max(2,step*.56));rect.setAttribute('height',Math.max(2,Math.abs(y(c.open)-y(c.close))));rect.setAttribute('class',c.close>=c.open?'candle-up':'candle-down');svg.appendChild(rect);closes.push([x,y(c.close)]);let vh=(c.volume/6000)*42;let vr=document.createElementNS('http://www.w3.org/2000/svg','rect');vr.setAttribute('x',x-step*.28);vr.setAttribute('y',B-vh);vr.setAttribute('width',Math.max(2,step*.56));vr.setAttribute('height',vh);vr.setAttribute('class',c.close>=c.open?'bar-up':'bar-down');svg.appendChild(vr)});
path(svg,closes.slice(4).map((_,idx)=>{let arr=closes.slice(idx,idx+5);return [arr[4][0],arr.reduce((s,p)=>s+p[1],0)/5]}),'ma5','#ffd45a',1.6);path(svg,closes.slice(19).map((_,idx)=>{let arr=closes.slice(idx,idx+20);return [arr[19][0],arr.reduce((s,p)=>s+p[1],0)/20]}),'ma20','#39a9ff',1.4);path(svg,closes.slice(39).map((_,idx)=>{let arr=closes.slice(idx,idx+40);return [arr[39][0],arr.reduce((s,p)=>s+p[1],0)/40]}),'ma60','#b064ff',1.2);
svgText(svg,L+22,y(DATA.technical.low)+12,'近期低點 '+DATA.technical.low,'start','#18d96b');svgText(svg,R-120,y(DATA.technical.high)-8,'近期高點 '+DATA.technical.high,'start','#ff3b3b')}
function drawOsc(id,val,color,label){let {svg,w,h,L,T,R,B}=setupSvg(id,420,64);let pts=[];for(let i=0;i<42;i++){let v=45+Math.sin(i/4)*10+(i>30?(i-30)*(val-55)/12:0);v=Math.max(5,Math.min(98,v));pts.push([L+i*(R-L)/41,B-v/100*(B-T)])}path(svg,pts,'',color,2);[30,70].forEach(v=>svgLine(svg,L,B-v/100*(B-T),R,B-v/100*(B-T),'axis'));svgText(svg,R-4,T+10,label,'end','#ffd45a')}
function drawMacd(){let {svg,w,h,L,T,R,B}=setupSvg('#macdChart',420,64);let mid=(T+B)/2;for(let i=0;i<34;i++){let x=L+i*(R-L)/34;let v=Math.sin(i/5)*13+(i>22?(i-22)*1.5:0);let rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x);rect.setAttribute('y',v>0?mid-v:mid);rect.setAttribute('width',6);rect.setAttribute('height',Math.abs(v));rect.setAttribute('class',v>0?'bar-up':'bar-down');svg.appendChild(rect)}let pts1=[],pts2=[];for(let i=0;i<42;i++){let x=L+i*(R-L)/41;pts1.push([x,mid- Math.sin(i/6)*8-(i>26?(i-26)*.9:0)]);pts2.push([x,mid- Math.sin(i/7)*6-(i>28?(i-28)*.55:0)])}path(svg,pts1,'','#ffd45a',2);path(svg,pts2,'','#39a9ff',2)}
function drawChip(){let {svg,w,h,L,T,R,B}=setupSvg('#chipChart',360,195);let rows=[...DATA.chips.institutional].reverse();let max=650,min=-650;let y=v=>B-(v-min)/(max-min)*(B-T), zero=y(0), step=(R-L)/rows.length;svgLine(svg,L,zero,R,zero,'axis');rows.forEach((r,i)=>{let x=L+i*step+6;[['foreign','#39a9ff'],['trust','#ff3b3b'],['dealer','#b064ff'],['total','#18d96b']].forEach(([k,c],j)=>{let v=r[k], yy=y(v);let rect=document.createElementNS('http://www.w3.org/2000/svg','rect');rect.setAttribute('x',x+j*5);rect.setAttribute('y',Math.min(yy,zero));rect.setAttribute('width',4);rect.setAttribute('height',Math.max(1,Math.abs(yy-zero)));rect.setAttribute('fill',c);svg.appendChild(rect)});svgText(svg,x,B+12,r.date.slice(3),'middle')});let pricePts=rows.map((r,i)=>[L+i*step+step/2,B-(150+i*6 + (i>7?25:0)-120)/(225-120)*(B-T)]);path(svg,pricePts,'','#ffd45a',3);svgText(svg,L,T+8,'外資 投信 自營商 合計 / 股價','#ffd45a')}
function drawBrokerFlow(){let b=DATA.chips.brokers||{top_buy:[],top_sell:[],summary:{},warning:'尚未接入分點資料'};$('#brokerDate').textContent=b.date?`(${b.date})`:'';let list=(rows,cls)=>`<div class="broker-list ${cls}">${rows.slice(0,5).map(r=>`<div class="broker-row"><span>${r.broker}</span><b class="${r.net>=0?'up':'down'}">${r.net>0?'+':''}${r.net}</b></div>`).join('')||'<div class="broker-empty">待接官方資料</div>'}</div>`;$('#brokerFlow').innerHTML=`<div><div class="broker-head up">買超前五大</div>${list(b.top_buy||[],'buy')}</div><div><div class="broker-head down">賣超前五大</div>${list(b.top_sell||[],'sell')}</div>`;let s=b.summary||{};$('#brokerStats').innerHTML=`<span>買集中 ${(s.buy_concentration*100||0).toFixed(0)}%</span><span>賣集中 ${(s.sell_concentration*100||0).toFixed(0)}%</span><span>Top5 淨額 ${(s.net_top5||0)>0?'+':''}${s.net_top5||0} 張</span>`;$('#brokerWarning').textContent=b.warning||''}
function drawTables(){let inst='<tr><th>日期</th><th>外資</th><th>投信</th><th>自營商</th><th>合計</th></tr>'+DATA.chips.institutional.slice(0,5).map(r=>`<tr><td>${r.date}</td>${['foreign','trust','dealer','total'].map(k=>`<td class="${r[k]>=0?'up':'down'}">${r[k]}</td>`).join('')}</tr>`).join('');$('#instTable').innerHTML=inst;drawBrokerFlow();let score='<tr><th>項目</th><th>星等</th><th>評語</th></tr>'+DATA.scores.map(r=>`<tr><td>${r.item}</td><td class="stars">${'★'.repeat(r.stars)}${'☆'.repeat(5-r.stars)}</td><td>${r.comment}</td></tr>`).join('');$('#scoreTable').innerHTML=score}
function init(){bind();drawK();drawOsc('#rsiChart',DATA.technical.rsi,'#ffd45a','0 / 30 / 70 / 100');drawMacd();drawOsc('#kdChart',DATA.technical.kd.k,'#ffd45a','K / D');drawChip();drawTables();document.body.dataset.ready='1'}
if(DATA) init();